"""Shared roster builder for training-data collection (TD + policy self-play).

Both collectors previously seeded their "champion" seat from
``scripts.champion_loop.BASE_CHAMPION_PARAMS`` — the *cold-start* config
(random rollouts, RAVE on, cutoff 5), not the promoted registry champion — so
every trajectory / visit-count target was generated by an agent much weaker
than the one being trained. This module resolves the **current registry
champion** and applies a named search profile (default ``teacher``: higher
iteration budget + progressive widening) so training labels come from a
strictly stronger searcher than the agent that will consume them.
"""

from __future__ import annotations

import copy
from typing import Any, Dict, List, Optional

from mcts.search_profiles import apply_search_profile


def champion_agent_config(name: str = "champion") -> Dict[str, Any]:
    """The registry champion as an arena agent config (cold-start fallback)."""
    try:
        from mcts_lab._common import load_state

        state = load_state()
        cfg = copy.deepcopy(state["champion_params"])
    except Exception:
        from scripts.champion_loop import BASE_CHAMPION_PARAMS

        cfg = copy.deepcopy(BASE_CHAMPION_PARAMS)
    cfg["name"] = name
    return cfg


def champion_version() -> str:
    """The champion registry version string (e.g. ``gen140``), or ``unknown``."""
    try:
        from training import TrainingPaths, state_store

        champion = state_store.load_champion(TrainingPaths.default())
        return str((champion or {}).get("version") or "unknown")
    except Exception:
        return "unknown"


def teacher_roster(profile: Optional[str] = "teacher") -> List[Dict[str, Any]]:
    """Two profiled champion seats plus heuristic/random opponents.

    The champion seats generate the training signal (their trajectories /
    visit targets are what gets captured); the weak seats diversify the board
    states reached. ``profile=None`` keeps the champion's own stored budget.
    """
    champ = champion_agent_config("champion")
    champ2 = champion_agent_config("champion2")
    if profile:
        champ = apply_search_profile(champ, profile)
        champ2 = apply_search_profile(champ2, profile)
    return [
        champ,
        {"name": "heuristic", "type": "heuristic"},
        champ2,
        {"name": "random", "type": "random"},
    ]
